In [1]:
import pandas as pd

df = pd.read_parquet("/home/nabin2004/Desktop/projects/lichess/data/processed/2013-01.parquet")
print(df.shape, df.columns.tolist())

(121332, 18) ['event', 'site', 'date', 'round', 'white', 'black', 'result', 'utc_date', 'utc_time', 'white_elo', 'black_elo', 'white_rating_diff', 'black_rating_diff', 'eco', 'opening', 'time_control', 'termination', 'moves']

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 121332 entries, 0 to 121331
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   event              121332 non-null  str
 1   site               121332 non-null  str
 2   date               121332 non-null  str
 3   round              121332 non-null  str
 4   white              121332 non-null  str
 5   black              121332 non-null  str
 6   result             121332 non-null  str
 7   utc_date           121332 non-null  str
 8   utc_time           121332 non-null  str
 9   white_elo          121254 non-null  float64
 10  black_elo          121192 non-null  float64
 11  white_rating_diff  121114 non-null  float64
 12  black_rating_diff  121114 non-null  float64
 13  eco                121332 non-null  str
 14  opening            121332 non-null  str
 15  time_control       121332 non-null  str
 16  termination        121332 non-null  str
 17  moves              121332 non-null  object
dtypes: float64(4), object(1), str(13)
memory usage: 32.8+ MB

In [4]:
df['moves']

0         [e2e4, e7e6, d2d4, b7b6, a2a3, c8b7, b1c3, g8h...
1         [d2d4, d7d5, g1f3, g8f6, e2e3, c8f5, f3h4, f5g...
2         [e2e4, e7e5, g1f3, b8c6, f1c4, g8f6, b1c3, f8c...
3         [e2e4, c7c6, b1c3, d7d5, d1f3, d5e4, c3e4, b8d...
4         [e2e4, e7e6, f2f4, d7d5, e4e5, c7c5, g1f3, d8b...
                                ...
121327    [d2d4, g8f6, c2c4, g7g6, b1c3, f8g7, e2e4, d7d...
121328    [e2e4, d7d5, d2d3, d5e4, d3e4, d8d1, e1d1, b8c...
121329    [e2e4, d7d5, e4d5, d8d5, b1c3, d5d8, g1f3, b8c...
121330    [e2e4, f7f6, f1c4, e7e6, d2d4, d8e7, b1c3, b8c...
121331    [e2e4, c7c6, d2d4, d7d5, b1c3, d5e4, c3e4, g8f...
Name: moves, Length: 121332, dtype: object

In [5]:
df.explode('moves', ignore_index=True)

,event,site,date,round,white,black,result,utc_date,utc_time,white_elo,black_elo,white_rating_diff,black_rating_diff,eco,opening,time_control,termination,moves
0,Rated Classical game,https://lichess.org/j1dkb5dw,????.??.??,?,BFG9k,mamalak,1-0,2012.12.31,23:01:03,1639.0,1403.0,5.0,-8.0,C00,French Defense: Normal Variation,600+8,Normal,e2e4
1,Rated Classical game,https://lichess.org/j1dkb5dw,????.??.??,?,BFG9k,mamalak,1-0,2012.12.31,23:01:03,1639.0,1403.0,5.0,-8.0,C00,French Defense: Normal Variation,600+8,Normal,e7e6
2,Rated Classical game,https://lichess.org/j1dkb5dw,????.??.??,?,BFG9k,mamalak,1-0,2012.12.31,23:01:03,1639.0,1403.0,5.0,-8.0,C00,French Defense: Normal Variation,600+8,Normal,d2d4
3,Rated Classical game,https://lichess.org/j1dkb5dw,????.??.??,?,BFG9k,mamalak,1-0,2012.12.31,23:01:03,1639.0,1403.0,5.0,-8.0,C00,French Defense: Normal Variation,600+8,Normal,b7b6
4,Rated Classical game,https://lichess.org/j1dkb5dw,????.??.??,?,BFG9k,mamalak,1-0,2012.12.31,23:01:03,1639.0,1403.0,5.0,-8.0,C00,French Defense: Normal Variation,600+8,Normal,a2a3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8155182,Rated Blitz game,https://lichess.org/e4gb7ja6,????.??.??,?,pablotorre,Tortfeasor,0-1,2013.01.31,22:59:31,1744.0,1762.0,-10.0,19.0,B15,Caro-Kann Defense: Forgacs Variation,300+0,Time forfeit,g5f4
8155183,Rated Blitz game,https://lichess.org/e4gb7ja6,????.??.??,?,pablotorre,Tortfeasor,0-1,2013.01.31,22:59:31,1744.0,1762.0,-10.0,19.0,B15,Caro-Kann Defense: Forgacs Variation,300+0,Time forfeit,d5c4
8155184,Rated Blitz game,https://lichess.org/e4gb7ja6,????.??.??,?,pablotorre,Tortfeasor,0-1,2013.01.31,22:59:31,1744.0,1762.0,-10.0,19.0,B15,Caro-Kann Defense: Forgacs Variation,300+0,Time forfeit,f6g5
8155185,Rated Blitz game,https://lichess.org/e4gb7ja6,????.??.??,?,pablotorre,Tortfeasor,0-1,2013.01.31,22:59:31,1744.0,1762.0,-10.0,19.0,B15,Caro-Kann Defense: Forgacs Variation,300+0,Time forfeit,c4b3
8155186,Rated Blitz game,https://lichess.org/e4gb7ja6,????.??.??,?,pablotorre,Tortfeasor,0-1,2013.01.31,22:59:31,1744.0,1762.0,-10.0,19.0,B15,Caro-Kann Defense: Forgacs Variation,300+0,Time forfeit,g5g4

In [6]:
df['eco']

0         C00
1         D04
2         C50
3         B12
4         C00
         ...
121327    E80
121328    B01
121329    B01
121330    B00
121331    B15
Name: eco, Length: 121332, dtype: str

In [7]:
df

,event,site,date,round,white,black,result,utc_date,utc_time,white_elo,black_elo,white_rating_diff,black_rating_diff,eco,opening,time_control,termination,moves
0,Rated Classical game,https://lichess.org/j1dkb5dw,????.??.??,?,BFG9k,mamalak,1-0,2012.12.31,23:01:03,1639.0,1403.0,5.0,-8.0,C00,French Defense: Normal Variation,600+8,Normal,"[e2e4, e7e6, d2d4, b7b6, a2a3, c8b7, b1c3, g8h..."
1,Rated Classical game,https://lichess.org/a9tcp02g,????.??.??,?,Desmond_Wilson,savinka59,1-0,2012.12.31,23:04:12,1654.0,1919.0,19.0,-22.0,D04,"Queen's Pawn Game: Colle System, Anti-Colle",480+2,Normal,"[d2d4, d7d5, g1f3, g8f6, e2e3, c8f5, f3h4, f5g..."
2,Rated Classical game,https://lichess.org/szom2tog,????.??.??,?,Kozakmamay007,VanillaShamanilla,1-0,2012.12.31,23:03:15,1643.0,1747.0,13.0,-94.0,C50,Four Knights Game: Italian Variation,420+17,Normal,"[e2e4, e7e5, g1f3, b8c6, f1c4, g8f6, b1c3, f8c..."
3,Rated Bullet game,https://lichess.org/rklpc7mk,????.??.??,?,Naitero_Nagasaki,800,0-1,2012.12.31,23:04:57,1824.0,1973.0,-6.0,8.0,B12,Caro-Kann Defense: Goldman Variation,60+1,Normal,"[e2e4, c7c6, b1c3, d7d5, d1f3, d5e4, c3e4, b8d..."
4,Rated Bullet game,https://lichess.org/1xb3os63,????.??.??,?,nichiren1967,Naitero_Nagasaki,0-1,2012.12.31,23:02:37,1765.0,1815.0,-9.0,9.0,C00,French Defense: La Bourdonnais Variation,60+1,Normal,"[e2e4, e7e6, f2f4, d7d5, e4e5, c7c5, g1f3, d8b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121327,Rated Classical game,https://lichess.org/4w6vfr19,????.??.??,?,Yudhisthira,netsah08,0-1,2013.01.31,22:59:08,1854.0,1937.0,-9.0,16.0,E80,King's Indian Defense: Saemisch Variation,600+10,Normal,"[d2d4, g8f6, c2c4, g7g6, b1c3, f8g7, e2e4, d7d..."
121328,Rated Classical game,https://lichess.org/33p7nthu,????.??.??,?,Daler,kualalumpur,0-1,2013.01.31,22:59:13,1500.0,1266.0,-331.0,12.0,B01,Scandinavian Defense,720+0,Time forfeit,"[e2e4, d7d5, d2d3, d5e4, d3e4, d8d1, e1d1, b8c..."
121329,Rated Classical game,https://lichess.org/pzncnhrt,????.??.??,?,senip,Richard_XII,0-1,2013.01.31,22:59:27,1431.0,1523.0,-70.0,7.0,B01,Scandinavian Defense: Mieses-Kotroc Variation,960+6,Normal,"[e2e4, d7d5, e4d5, d8d5, b1c3, d5d8, g1f3, b8c..."
121330,Rated Blitz game,https://lichess.org/hhwb2whr,????.??.??,?,van9,shueardm,1-0,2013.01.31,22:59:41,1693.0,1479.0,6.0,-5.0,B00,Barnes Defense,180+1,Normal,"[e2e4, f7f6, f1c4, e7e6, d2d4, d8e7, b1c3, b8c..."
121331,Rated Blitz game,https://lichess.org/e4gb7ja6,????.??.??,?,pablotorre,Tortfeasor,0-1,2013.01.31,22:59:31,1744.0,1762.0,-10.0,19.0,B15,Caro-Kann Defense: Forgacs Variation,300+0,Time forfeit,"[e2e4, c7c6, d2d4, d7d5, b1c3, d5e4, c3e4, g8f..."